spring.application.name=realtime-messaging-backend

spring.datasource.url=jdbc:mysql://localhost:3306/realtime_chat_db
spring.datasource.username=root
spring.datasource.password=8359

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=

server.port=${PORT:8080}